spring:
  application:
    name: JWT Demo
  profiles:
    active: test
  
---
spring:
    profiles: test
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: null
#      tomcat:
#        max-wait: 20000
#        max-active: 50
#        max-idle: 20
#        min-idle: 15
      hikari: 
        pool-name: hikari-cp
        maximum-pool-size: 2 
        minimum-idle: 2
        data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 10
          prepStmtCacheSqlLimit: 10
          useServerPrepStmts: true
    jpa:
      database: H2
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
---
mybatis:
    mapper-locations: classpath*:META-INF/mybatis/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
